[package]
name = "lux-tracer"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.48", features = ["derive"] }
image = "0.25.8"
indicatif = { version = "0.18.0", features = ["rayon"] }
rayon = "1.11.0"
sobol = "1.0.2"
tobj = "4.0.3"

[profile.release]
lto = "thin"
